In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
# creating empty lists top store the data.

crypto_name_list = []
crypto_market_cap_list = []
crypto_price_list = []
crypto_circulating_supply_list = []
crypto_symbol_list = []

In [3]:
# creating a func to scrape the data.
# https://coinmarketcap.com/historical/20240602/
def scrape(date = '20240602/'):

    # formatting the date here.
    [year, month, day] = date[:4], date[4:6], date[6:8]
    format_date = "-".join([day, month, year])
    print(format_date)
    
    # get the URL
    url = 'https://coinmarketcap.com/historical/' + date
    # make request to the website.
    webpage = requests.get(url=url)
    # parse the text from the website here.
    soup = BeautifulSoup(webpage.text, 'html.parser')

    # get the table row elements
    tr = soup.find_all('tr', attrs={'class' : 'cmc-table-row'})
    print(f"Total Rows Fetched : {len(tr)}")
    # create a count variable for the number of crypto currencies that we want to scrape.
    count = 0
    # loop through every table-row to gather the data.
    for row in tr:
        # if count is reached then break out of the loop.
        if count == 20:
            print(f'Current Rows Fetched : {count}')
            break
        count += 1

        # store the name of the crypto-currency into a var here.
        name_column = row.find('td', attrs = {'class': 'cmc-table__cell cmc-table__cell--sticky cmc-table__cell--sortable cmc-table__cell--left cmc-table__cell--sort-by__name'})
        crypto_name = name_column.find('a', attrs = {'class': 'cmc-table__column-name--name cmc-link'}).text.strip()

        # store the coin market cap of the crypto or coin into a var here.
        crypto_market_cap = row.find('td', attrs = {'class': 'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__market-cap'}).text.strip()

        # find and store the crypto price
        crypto_price = row.find('td', attrs={'class': 'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__price'}).text.strip()
        
        # find and store the crypto supply
        crypto_circulating_supply_symbol = row.find('td', attrs={'class': 'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__circulating-supply'}).text.strip()
        # splitting the data here
        crypto_circulating_supply = crypto_circulating_supply_symbol.split(' ')[0]
        crypto_circulating_symbol = crypto_circulating_supply_symbol.split(' ')[1]

        # appending the extracted data to the global lists here.
        crypto_name_list.append(crypto_name)
        crypto_market_cap_list.append(crypto_market_cap)
        crypto_price_list.append(crypto_price)
        crypto_circulating_supply_list.append(crypto_circulating_supply)
        crypto_symbol_list.append(crypto_circulating_symbol)

In [4]:
# executing the func here.
scrape(date = '20240602/')

02-06-2024
Total Rows Fetched : 200
Current Rows Fetched : 20

In [5]:
# store the data into the dataframe.
data = {
    "Name" : crypto_name_list,
    "Symbol" : crypto_symbol_list,
    "Market Cap" : crypto_market_cap_list,
    "Price" : crypto_price_list,
    "Circulating Supply" : crypto_circulating_supply_list,
}
df = pd.DataFrame(data)

In [6]:
df

,Name,Symbol,Market Cap,Price,Circulating Supply
0,Bitcoin,BTC,"$1,335,182,728,999.50","$67,751.60","19,707,028"
1,Ethereum,ETH,"$454,251,771,430.25","$3,780.90","120,143,951"
2,Tether USDt,USDT,"$112,143,042,658.35",$0.9994,"112,210,010,735"
3,BNB,BNB,"$88,997,799,990.63",$603.03,"147,585,192"
4,Solana,SOL,"$75,044,190,328.87",$163.25,"459,689,022"
5,USDC,USDC,"$32,358,981,689.65",$0.9999,"32,361,934,446"
6,XRP,XRP,"$28,472,741,617.33",$0.5135,"55,450,358,947"
7,Dogecoin,DOGE,"$22,723,181,720.53",$0.1572,"144,549,006,384"
8,Toncoin,TON,"$16,447,920,886.58",$6.8183,"2,412,320,622"
9,Cardano,ADA,"$15,942,185,276.42",$0.4465,"35,705,255,566"
10,Shiba Inu,SHIB,"$14,509,708,504.96",$0.00002462,"589,271,824,650,943"
11,Avalanche,AVAX,"$13,733,422,855.50",$34.93,"393,141,819"
12,Chainlink,LINK,"$10,655,028,400.37",$18.15,"587,099,970"
13,Polkadot,DOT,"$10,049,913,470.61",$6.9890,"1,437,953,431"
14,TRON,TRX,"$10,022,665,438.04",$0.1147,"87,364,767,365"
15,Bitcoin Cash,BCH,"$9,035,870,717.62",$458.34,"19,714,144"
16,NEAR Protocol,NEAR,"$7,781,565,045.27",$7.1942,"1,081,640,339"
17,Polygon,MATIC,"$6,835,433,971.71",$0.6899,"9,907,380,055"
18,Litecoin,LTC,"$6,195,734,538.03",$83.05,"74,599,087"
19,Pepe,PEPE,"$6,159,540,822.45",$0.00001464,"420,689,899,999,995"

In [7]:
df.to_csv("Top_20_Coins")